on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

    - working-directory: site
    - run: npm install

    - working-directory: site
    - run: npm run build --if-present

      working-directory: site
    - run: cp -R ./* /var/www/trexame/

    - working-directory: api
    - run: npm install

    - working-directory: api
    - run: cp -R ./* /repos/trexame/api/
    